databases:
  - name: marketzo-postgres
    plan: free
    databaseName: marketzo_db
    user: marketzo_user

services:
  - type: web
    name: marketzo
    env: node
    plan: free
    buildCommand: npm install && npm --prefix client install && npm --prefix client run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketzo-postgres
          property: connectionString
